luset_valve_config:
    # Specify which actuators (right column) are connected to which valves (left column)
    T100:
        - "T101"
        - "T102"
        - "T103"
        - "T104"
        - "T105"
    T200:
        - "T201"
        - "T202"
        - "T203"
        - "T204"
        - "T205"
    T300:
        - "T301"
        - "T302"
        - "T303"
        - "T304"
        - "T305"
    T400:
        - "T401"
        - "T402"
        - "T403"
        - "T404"
        - "T405"
    T500:
        - "T501"
        - "T502"
        - "T503"
        - "T504"
        - "T505"
    S100:
        - "S101"
        - "S102"
        - "S103"
        - "S104"
        - "S105"
    S200:
        - "S201"
        - "S202"
        - "S203"
        - "S204"
        - "S205"
    S300:
        - "S301"
        - "S302"
        - "S303"
        - "S304"
        - "S305"
    S400:
        - "S401"
        - "S402"
        - "S403"
        - "S404"
        - "S405"
    S500:
        - "S501"
        - "S502"
        - "S503"
        - "S504"
        - "S505"
    B100:
        - "B101"
        - "B102"
        - "B103"
        - "B104"
        - "B105"
    B200:
        - "B201"
        - "B202"
        - "B203"
        - "B204"
        - "B205"
    B300:
        - "B301"
        - "B302"
        - "B303"
        - "B304"
        - "B305"
    B400:
        - "B401"
        - "B402"
        - "B403"
        - "B404"
        - "B405"
    B500:
        - "B501"
        - "B502"
        - "B503"
        - "B504"
        - "B505"
    N100:
        - "N101"
        - "N102"
        - "N103"
        - "N104"
        - "N105"
    N200:
        - "N201"
        - "N202"
        - "N203"
        - "N204"
        - "N205"
    N300:
        - "N301"
        - "N302"
        - "N303"
        - "N304"
        - "N305"
    N400:
        - "N401"
        - "N402"
        - "N403"
        - "N404"
        - "N405"
    N500:
        - "N501"
        - "N502"
        - "N503"
        - "N504"
        - "N505"